blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView, ListView, CreateView

from blog import views
from . views import (
        comment_approve,
        comment_remove,
        PostListView,
        PostDetailView,
        CommentFormView
        )


urlpatterns = [
        url(r'^blog/$', PostListView.as_view(), name='list'),
        url(r'^(?P<slug>[\w-]+)/$', PostDetailView.as_view(), name='detail'),
        url(r'^form/$', CommentFormView.as_view(), name='form'),
        url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
        url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
        ]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from blog import views
from blog.views import PostListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', PostListView.as_view(), name='list'),
    url(r'^blog', include('blog.urls', namespace='blog')),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
import datetime
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.utils import timezone
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(null=True, blank=True)
    publish = models.BooleanField(default=True)
    pub_date = models.DateTimeField('date_published')


    def __str__(self):
        return self.title


    def was_published_recently(self):
        now = timezone.now()


        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_discription = 'Latest Publish'


    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug':self.slug})

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-pub_date"]


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', null=True)
    name = models.CharField(max_length=150)
    email = models.EmailField(null=True, blank=True, default="Enter Valid Email Address")
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)


    def comments_approved(self):
        alert = "Approved"
        NotAlert = "Not Approved"
        if self.approved_comment == True:
            return alert
        else:
            return NotAlert
        self.save()

    def __str__(self):
        return self.name


    def get_abolute_url(self):
        return reverse('blog:detail', kwargs={'slug':self.name})


def entry_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


def entry_post_save_receiver(sender, instance, created, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
        instance.save() 


pre_save.connect(entry_pre_save_receiver, sender=Post)
post_save.connect(entry_post_save_receiver, sender=Post)

blog/forms.py
from django import forms

from .models import Post, Comment


class CommentForm(forms.ModelForm):
    #comment_area = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Comment
        fields = ['name',
                'email',
                'text',]

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView

from .models import Post, Comment
from .forms import CommentForm

# Create your views here.

def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve

    return redirect('blog/post_detail', pk=comment.post.pk)


def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()

    return redirect('blog/post_detail', pk=comment.post.pk)

class PostListView(ListView):
    queryset = Post.objects.all()
    template_name = 'blog/post_list.html'


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    form_class = CommentForm
    template_name = 'blog/post_detail.html'


    def post(self, request, slug, *args, **kwargs):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, slug=slug)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.get_object()
            #comment.post = post.get_object()
            comment.save()

            self.object = self.get_object()
            context = context = super().get_context_data(**kwargs)
            context['form'] = CommentForm

            return self.render_to_response(context=context)
            
        else:
            #form = CommentForm()
            self.object = self.get_object()
            context = super().get_context_data(**kwargs)
            context['form'] = form

            return self.render_to_response(context=context)

            
    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.request.comments
        return super(PostDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm
        
        return context

    success_url = '/blog/'


class CommentFormView(FormView):
    #queryset = Comment.objects.all()
    form_class = CommentForm
    success_url = '/blog/'

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block head_title %} Detail || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1> Post Content </h1>

<p> Post Detail coming through </p>

Post Title: {{ object.title }}<br />
Author: {{ object.author}}<br />
Content: {{ object.body }}<br />

{{ object.pub_date }}, {{ object.pub_date|timesince }} ago

<hr>

	<h1> Drop your comment bellow </h1>
	<form method='POST'> {% csrf_token %}
		{{ form.as_p }}
	<button type='submit'> Comment</button>
	</form>


	<br />

{% for comment in post.comments.all %}

{% if comment.approved_comment %}
<div class='comment'>
	<div class='date'>
		{{ comment.created_date }}
		{% if not comment.approved_comment %}
		<a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
		<a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
		{% endif %}
	</div>
	<strong>{{ comment.name }}</strong>
	<p>{{ comment.text|linebreaks }}</p>
</div>

{% endif %}

{% empty %}

<p> No comments here yet </p>

{% endfor %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block head_title %} Home || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1> Home Page <h1>
		<p> Blog list is coming through </p>

<h2> Blog List </h2>

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>

<ul>
	{% for post in object_list %}
	<li><a href='{{ post.get_absolute_url }}'>{{ post }}</a><br />
		Blog Title : {{ post.title}}<br />
		Author: {{ post.author }}<br />
		Content: {{ post.body }} <br />

		{{post.pub_date}}, {{ post.updates|timesince }} ago </li>
	<br />
	<a href='{{ post.get_absolute_url }}'>Comments: {{ post.approved_comments.count }} </a>
	<br />
	{% endfor %}

</ul>
</div>

{% endblock %}

templates/base.html
<!Doctype html>
<html lang=en>

	<head>
		<title>{% block head_title %} Em-Jay.com {% endblock head_title %}</title>
	</head>

	<body>
		{% include "snippets/nav.html" %}

		<div class='container'>
			{% block content %}

			{% endblock %}
		</div>

	</body>

</html>

templates/form.html
{% extends 'base.html' %}

{% block head_title %} Dummy_Form || {{ block.super }}{% endblock head_title %}

{% block content %}
{% include 'snippets/form-snippet.html' %}

{% endblock %}

templates/snippets/form-snippet.html
{% if form.error.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST'> {% csrf_token %}
	{{ form.as_p }}
	<button type='submit'>Comment</button>
</form>

templates/snippets/nav.html
<div class='container'>
	<h1>infoMingo.com</h1>
	<a href='{% url "blog:list" %}'>Home</a>
	<a href='{% url "about" %}'>About Me</a>
	<a href='{% url "contact" %}'>Contact Me</a>